### ISSUE TITLE
Group the `teams` page like the `Our work` page.

### ISSUE THREAD

**Issue by Anindyadeep** [CORD-ai/cord-website#10]
The initial `Teams` page looks like this.

![image](https://user-images.githubusercontent.com/58508471/184548201-09ef47c2-a3e2-40be-83fe-f05d83d50d45.png)

And the initial `Our work` section looks like this.

![image](https://user-images.githubusercontent.com/58508471/184548259-351f0ea5-f404-420f-966b-bb5183ce45f6.png)

As we can see that the stuffs can be grouped in `projects`, `Blogs` and `Sessions`. Similarly, using the same way, we want to group the `Teams` page in `All`, `Core Team`, `Community managers`, `Contributors`. 

Though the individual cards in teams i.e. `hovering will show the credentials of the person` will remain same. All we want to do is group them based on categories like `Our work` section.

**Comment by Joshua-Nweze** [comment]
Hi, I'll lovfe to work on this one

**Comment by Anindyadeep** [comment]
> Hi, I'll love to work on this one

Yeah sure. Go Ahead @Joshua-Nweze. Please let me know if you want need more info about what exactly we need to get implemented.

**Comment by Joshua-Nweze** [comment]
How do I know which category to put each member of the team in?

**Comment by Anindyadeep** [comment]
> How do I know which category to put each member of the team in?

For now, we want the structure to be done. And initially for testing purposes locally, put randomly some profiles to core, community managers and contributors. If you see stuffs are working properly. Let us know. When you will be pushing your changes, then please regroup every profile to core-groups. 

After that I will be providing the profiles of Community managers and contributors separately. And integrate those changes before the merge.

**Comment by Joshua-Nweze** [comment]
I've created a PR, it works

**Comment by Anindyadeep** [comment]
Lemme check, btw is it merged?

**Comment by Nikunjbansal99** [comment]
@Anindyadeep Is it done?

**Comment by Anindyadeep** [comment]
@Joshua-Nweze Hi, you have done quite a great work. But in any case can you group the teams with 4 columns instead of 3. The cards are looking very big. So can you look into this. I guess after this we can close this issues.

**Comment by AneeshBose** [comment]
> @Joshua-Nweze Hi, you have done quite a great work. But in any case can you group the teams with 4 columns instead of 3. The cards are looking very big. So can you look into this. I guess after this we can close this issues.

I actually quite like the current way it is implemented... :( Do we want to change it?

**Comment by Anindyadeep** [comment]
> > @Joshua-Nweze Hi, you have done quite a great work. But in any case can you group the teams with 4 columns instead of 3. The cards are looking very big. So can you look into this. I guess after this we can close this issues.
> 
> I actually quite like the current way it is implemented... :( Do we want to change it?

Nah there is no mandatory in this.... It's just the cards very big. Otherwise it's just minor stuff. Lol

**Comment by AneeshBose** [comment]
@Joshua-Nweze Would you like to incorporate any further changes in your PR linked to this issue?
