### ISSUE TITLE
Group the projects.

### ISSUE THREAD

**Issue by Anindyadeep** [CORD-ai/cord-website#11]
Once all the cards are added, group them on the required categories like `Projects`, `Blogs`, `Sessions`.

**Comment by AneeshBose** [comment]
I'll take a stab at this once the projects actively worked on are added to CORD.

**Comment by Anindyadeep** [comment]
cool.

**Comment by AneeshBose** [comment]
@AdityaKapoor74 @Nikunjbansal99 Since y'all are also working on projects which are to be added to CORD, could you add your projects to the page as well?

**Comment by Nikunjbansal99** [comment]
Sure. I will add.

**Comment by Nikunjbansal99** [comment]
> @AdityaKapoor74 @Nikunjbansal99 Since y'all are also working on projects which are to be added to CORD, could you add your projects to the page as well?

Done. Pull Request Created.
