### ISSUE TITLE
Teams page - Community Managers and contributors 

### ISSUE THREAD

**Issue by Ash-29** [CORD-ai/cord-website#20]
Adding the coordinator's profile page in the teams section

**Comment by Ash-29** [comment]
I am working on the manager's page, but when I resized their image to 600x600 resolution, their photos were blurred. Anything which I can do @AneeshBose

**Comment by AneeshBose** [comment]
Ask them to provide a higher dimension pic of that resolution. Try other online resizers first?

**Comment by Nikunjbansal99** [comment]
#39 Merged

Closing this Issue
