### ISSUE TITLE
FAQs refinement based on discussion

### ISSUE THREAD

**Issue by AneeshBose** [CORD-ai/cord-website#24]
The FAQs for the CORD website need to be improved upon to paint the entire story for the organization.  CC - @AdityaKapoor74 for brainstorming on the points to add.

**Comment by AneeshBose** [comment]
Can we have this completed by today? @BalajiAI @AdityaKapoor74

**Comment by BalajiAI** [comment]
Sure @AneeshBose. Before editing the FAQs, I'll post here the content, and if it seems good, then I'll make a PR.

**Comment by AneeshBose** [comment]
Sure. You can discuss it with @AdityaKapoor74 too.

**Comment by BalajiAI** [comment]
**Do I need to have a solid mathematical background to get started in AI research?**
It helps, but not required when you're starting out. It also depends on the research project that you're involved in, For eg., NLP research projects doesn't require much math but projects on Optimization algorithms require a great deal of math. We also have a #math-for-ml slack channel, where you can ask doubts, and find a person to discuss topics regarding it. Yeah, You can learn the required math on the fly.

**Comment by BalajiAI** [comment]
### **What is the motivation behind this community?**
You can learn anything related to AI in online for free. You can read research papers from top AI labs for free in arxiv. This is one of the best times to get started in AI research. But there's a caveat, good quality research always results from a group of people. It's hard to find a right partner for your research, especially when you're not from a research university. So our community helps you to find right colloborators for your research.

**Comment by BalajiAI** [comment]
This is all that I can squeeze out of my brain !
I think we should also improve our existing FAQs.

**Comment by AneeshBose** [comment]
LGTM. You can add these to the FAQs
