### ISSUE TITLE
CORD.ai website icon.

### ISSUE THREAD

**Issue by Anindyadeep** [CORD-ai/cord-website#7]
Add a website icon to the nav bar and the footer. Where CORD.ai is written.

**Comment by AneeshBose** [comment]
This is high priority right now.

**Comment by AneeshBose** [comment]
@Ash-29 Any updates for this?

**Comment by Ash-29** [comment]
> @Ash-29 Any updates for this?

working

**Comment by Nikunjbansal99** [comment]
@Ash-29, done?

**Comment by Anindyadeep** [comment]
@Ash-29 whats the update?

**Comment by Anindyadeep** [comment]
Great Job.
