### ISSUE TITLE
Forms for new members to join.

### ISSUE THREAD

**Issue by Anindyadeep** [CORD-ai/cord-website#8]
Initial `Join our community` is linked with the `slack community` link. Instead of that, create a new website that consist of a form (This can be a free open source services but not **`google forms`**. One example is `typeform` (all though it is paid). 

The form website must contain this questions:
1. Name
2. College
3. Year of college
4. Country
5. Area of interest
6. GitHub, Linkedin, website (optional) links.
7. Why you want to join the community.
8. What you expect from this community.

Once the user will fill this form, then he/she will be directed to join the slack community. And at the same time, the information will be stored in any form of Database.

**Comment by Nikunjbansal99** [comment]
@Anindyadeep, Any Specific Reason for not using google Forms?

**Comment by Nikunjbansal99** [comment]
@Anindyadeep In my opinion, we can use the same google form with modified UI. Upon successful submission, it will redirect to our slack Channel ( as mentioned in Phase 1)

**Comment by Nikunjbansal99** [comment]
@Ash-29 Need Joining Form edit access.

**Comment by Nikunjbansal99** [comment]
This message will be shown on our Joining Form Submission Confirmation Page:
Welcome to CORD.ai Community. Join our Slack Channel using <slack joining link>

**Comment by Anindyadeep** [comment]
I guess we can close this issue for now. As the google forms is enabled for now.
