### ISSUE TITLE
Enable the `Newsletter` and `Contact us` services (SMTP). 

### ISSUE THREAD

**Issue by Anindyadeep** [CORD-ai/cord-website#9]
There is a pre implemented code for Contact us page back end for sending the `contact us` request. It is using SMTP services. Start with enabling the services. After that if required, change it to REST API services. This can be done by creating a second pull request.

**Comment by Nikunjbansal99** [comment]
@Anindyadeep I have done this previously. Can I help? Or Is it done?

**Comment by AneeshBose** [comment]
Any updates to this? @Anindyadeep @Nikunjbansal99

**Comment by Anindyadeep** [comment]
> Any updates to this? @Anindyadeep @Nikunjbansal99

Yesterday really grinded on SMTP and MailJS services. But could not stop by a solution. Today the whole day was really packed with assignments and stuff. So was't able to put much time on it. 

Though I had some time with @Nikunjbansal99 and he mentioned he can take a look on it. I hope we can do that by tomorrow. 

In the worst case scenerio, for now we can put out a seperate google form. Like we can write there mentioning, if there are interested folks who want to reach out for collaboration or something, then only fill this gForm , otherwise join the community. I am keeping this stuff for tomorrow. If by any chance, we can not fix the SMTP/MailJS thing then I guess we can go with that for initial iteration. Please let me know your thoughts.

**Comment by Nikunjbansal99** [comment]
> Any updates to this? @Anindyadeep @Nikunjbansal99

Yep, maybe we need Cpanel access to configure the PHP email service. I will confirm it today, and @AneeshBose will let you know. In that case, you need to purchase the domain and hosting plan first.

**Comment by Anindyadeep** [comment]
> > Any updates to this? @Anindyadeep @Nikunjbansal99
> 
> Yep, maybe we need Cpanel access to configure the PHP email service. I will confirm it today, and @AneeshBose will let you know. In that case, you need to purchase the domain and hosting plan first.

Yesss please move on to the discussion #33

**Comment by Anindyadeep** [comment]
I guess we can close this issue for now.
